services:
  - type: web
    name: resume-optimizer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        fromEnv: GROQ_API_KEY
